# Generated by Django 4.2.8 on 2023-12-05 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=150)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='helpdesk.category')),
            ],
            options={
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2023, 12, 5, 13, 19, 50, 237369, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('pub_update_time', models.DateTimeField(default=datetime.datetime(2023, 12, 5, 13, 19, 50, 237369, tzinfo=datetime.timezone.utc), verbose_name='date updated')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('slug', models.SlugField(max_length=150)),
                ('cat', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.category')),
            ],
        ),
    ]
