# Generated by Django 4.2.8 on 2023-12-05 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='helpdesk.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 14, 31, 27, 565854, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_update_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 14, 31, 27, 565854, tzinfo=datetime.timezone.utc), verbose_name='date updated'),
        ),
    ]
