# Generated by Django 4.2.8 on 2023-12-08 12:57

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_article_cat_alter_article_pub_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 57, 40, 142181, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_update_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 57, 40, 142181, tzinfo=datetime.timezone.utc), verbose_name='date updated'),
        ),
    ]
